### ISSUE TITLE
Dockerizing the system

### ISSUE THREAD

**Issue by Hamza-Mokiwa** [COS301-SE-2024/WorkWise-Central#102]
# Feature Request

## Description

The entire system (frontend, backend and DB) will be split into 3 separate containers that will be connected via Docker compose.

## Use Case

Deployment and consistency between developers.
Packaging all dependencies together

## Expected Behavior

- Developers will code in an identical/consistent environment
- The app will be easy to deploy and/or spin up

## Additional Information

It must work on the client's Provided platform.

---

### Note for Contributors:

**Feature Request Checklist:**

- [X] I have searched for similar feature requests before submitting this one.
- [X] I have provided a clear and descriptive title for the request.
- [X] I have assigned appropriate labels.
- [X] I have tagged the issue with the correct project milestone (if applicable).
- [X] I have provided all the requested information.

**Comment by JessBloem** [comment]
Can this issue please be closed and a new one made for the current work that needs to be done on Docker
