### ISSUE TITLE
Backend: Notification System

### ISSUE THREAD

**Issue by Hamza-Mokiwa** [COS301-SE-2024/WorkWise-Central#103]
# Feature Request

## Description

- Users should be able to receive notifications about important events that are relevant to them.
- Notifications may be through email or within the application itself. (To be Determined)

## Use Case

- Someone makes a request to join your company.
- A job that you are subscribed to has some event that has occurred
- You have an upcoming event

## Expected Behavior

- User must be notified

### Note for Contributors:

**Feature Request Checklist:**

- [X] I have searched for similar feature requests before submitting this one.
- [X] I have provided a clear and descriptive title for the request.
- [X] I have assigned appropriate labels.
- [X] I have tagged the issue with the correct project milestone (if applicable).
- [X] I have provided all the requested information.

**Comment by JessBloem** [comment]
Since this is needed for the joining of a company, I am going to update the sprint and the end date to correspond to that of the join company issue. Please adjust the dates of this issue if the whole issue will not be completed by that date

**Comment by Hamza-Mokiwa** [comment]
I am starting work on this today. @JessBloem

**Comment by JessBloem** [comment]
@Hamza-Mokiwa I am going to make a seperate issue for the notifications that needs to be done in the current sprint. please refere to that for the current sprint

**Comment by Hamza-Mokiwa** [comment]
It needs frontend FCM tokens to be tested, we will implement it today

**Comment by Hamza-Mokiwa** [comment]
@BlockchainDlamini said he will do this frontend token registration by the end of the day.
