### ISSUE TITLE
Employee task view

### ISSUE THREAD

**Issue by BlockchainDlamini** [COS301-SE-2024/WorkWise-Central#107]
# Feature Request

## Description

An employee task view that is a viewable interface to group employees and not manager and higher level roles within the sytem

## Use Case

Will be used by underlying technical employees to keep track of their tasks 

## Expected Behavior

N/A

## Additional Information

N/A 

---

### Note for Contributors:

**Feature Request Checklist:**

- [X] I have searched for similar feature requests before submitting this one.
- [X] I have provided a clear and descriptive title for the request.
- [X] I have assigned appropriate labels.
- [X] I have tagged the issue with the correct project milestone (if applicable).
- [X] I have provided all the requested information.

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by BlockchainDlamini** [comment]
Has been moved to Demo 3

**Comment by JessBloem** [comment]
Please update the sprint and the timeline of this issue as well. It this issue is not longer being used, please close it
