### ISSUE TITLE
System themes

### ISSUE THREAD

**Issue by BlockchainDlamini** [COS301-SE-2024/WorkWise-Central#108]
# Feature Request

## Description

Create system themes that will be utilised throughout the entire sytem

## Use Case

A preference based extendable colour scheme users of system will choose from

## Expected Behavior

N/A

## Additional Information

N/A 

---

### Note for Contributors:

**Feature Request Checklist:**

- [X] I have searched for similar feature requests before submitting this one.
- [X] I have provided a clear and descriptive title for the request.
- [X] I have assigned appropriate labels.
- [X] I have tagged the issue with the correct project milestone (if applicable).
- [X] I have provided all the requested information.

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
Please close or update this issue. It is pass it's due date
