### ISSUE TITLE
Database role modelling

### ISSUE THREAD

**Issue by BlockchainDlamini** [COS301-SE-2024/WorkWise-Central#109]
# Feature Request

## Description

An enhance database that robustly models the hierarchal nature of roles within the system

## Use Case

Will be utilised by the system for system views

## Expected Behavior

N/A

## Additional Information

N/A 

---

### Note for Contributors:

**Feature Request Checklist:**

- [X] I have searched for similar feature requests before submitting this one.
- [X] I have provided a clear and descriptive title for the request.
- [X] I have assigned appropriate labels.
- [X] I have tagged the issue with the correct project milestone (if applicable).
- [X] I have provided all the requested information.

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
Data base has been remodeled to account for the company hirachy.
