### ISSUE TITLE
User story: Delete jobs

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#111]
As a managerial user,
I want to be able to delete a jobs from the system
so that I may remove any job that should not be in the system any more.

Acceptance criteria:
- [ ] The user should only be able to delete jobs if they have the appropriate permissions
- [x] The deleted job must be flagged for deletion in the database

**Comment by BlockchainDlamini** [comment]
Works for mock data, needs data integration from APIs to be complete

**Comment by JessBloem** [comment]
Please make sure to close this issue once completed. I have update the due date to correspond to the new deadline.

**Comment by Hamza-Mokiwa** [comment]
It will be done today
