### ISSUE TITLE
Refactor theme changing button

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#199]
# Refactor Request

## Description

Please change the change theme button to use a icon instead of a button with words. Please also integrate system settings so that the user's prefererence is automatically used.

## Deliverables

- [x] Change theme button is now an icon
- [ ] The system settings have been integrated
---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
updated the button to be an icon

**Comment by JessBloem** [comment]
This issue was not fully completed by deadline. A new issue has been created with what still needs to be done
