### ISSUE TITLE
refactor company backend

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#211]
# Refactor Request

## Description

Please refactor the company backend in accordance with the deliveraables below

## Deliverables

- [x] Add 'company type' field to company entity as well as create company endpoint
- [x] Check that the company registration number sent in is formatted correctly
- [x] Ensure that the company name is required in the create company endpoint
- [ ] In the create company endpoint, call the service in roles that creates the defualt roles

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
I will let you know when I created the service that creates the defualt roles for a company

**Comment by JessBloem** [comment]
Please close o update this issue, since it is past it's due date

**Comment by Hamza-Mokiwa** [comment]
Roles service is outstanding, but will be completed this week @JessBloem

**Comment by Hamza-Mokiwa** [comment]
I now need to add tags, and priority, it will be done by the end of the week

**Comment by Hamza-Mokiwa** [comment]
Done.
