### ISSUE TITLE
Backend test

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#215]
# Chore

## Description

Please ensure that all test for backend are created and pass. Ensure that all endpoints are tested

## Deliverables 

- [ ] All endpoints have tests
- [ ] All integration tests have been done
- [x] All tests are passing 

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
@Hamza-Mokiwa has finished his tests. @JessBloem still has to finish some tests. This issue will be extended by 2 day max

**Comment by Hamza-Mokiwa** [comment]
I would like to still add more tests

**Comment by JessBloem** [comment]
Basic tests have been added. The issue will be closed and a new one will be opened once we work on it again
