### ISSUE TITLE
Frontend: Register Company

### ISSUE THREAD

**Issue by KumbiraiShonhiwa** [COS301-SE-2024/WorkWise-Central#22]
# Feature Request

## Description

Implmenting the base for the register company functionality

## Use Case
Authenication and Authorisation 

## Expected Behavior
Users should be able to register their companies with their details:
Number of employees
Industry that company is associated with
Contact Email 
Password
## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Feature Request Checklist:**

- [x] I have searched for similar feature requests before submitting this one.
- [x] I have provided a clear and descriptive title for the request.
- [x] I have assigned appropriate labels.
- [x] I have tagged the issue with the correct project milestone (if applicable).
- [x] I have provided all the requested information.

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by CodeHermez** [comment]
Register company works, makes calls to backend API, and registers the newly created company after you Signup's been done
