### ISSUE TITLE
Refactor company registration

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#251]
# Refactor Request

## Description

Please refactor in accourdance with the deliverables below

## Deliverables

- [x] Add validation to company phone number to check that it s 10 digits long
- [x] Add validation to the company registration number to check that the number is the correct format accourding to this https://www.inv24.co.za/za/blog/invoice_reg_nr/

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by CodeHermez** [comment]
Added validation for phone number and registration number for the company and the request is successful and can finally register a company successfully
