### ISSUE TITLE
Implement join company modal

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#252]
# Implementation Request

## Description

[Provide a clear and concise description of what needs to be refactored.]

## Deliverables

- [ ] Make the dropdown for the company names pull from the databse
- [ ] Make the dropdown searchable
- [ ] Make the words in the enter company id dialog box be a place holder
- [ ] Check that the enter company dialog box checks that the company id entered exists in the db
- [ ] Create modals add the role, supperior and subordinates of a new employee
- [ ] Finish the notification for the request to join a company
- [ ] Finish the email for notification
- [ ] Finish the join company endpoint

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by Hamza-Mokiwa** [comment]
I am going to work on this today, notifications is now in my backlog. @CodeHermez

**Comment by JessBloem** [comment]
Will create a new issue
