### ISSUE TITLE
Refactor navbar

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#254]
# Refactor Request

## Description

Please refactor the navbar in accordance with deliverables below

## Deliverables

- [ ] When the nave bar is collapsed, the expanded icons should still show. Refere to the example below
![image](https://github.com/COS301-SE-2024/WorkWise-Central/assets/133756137/da45c298-262d-4d89-8abf-f9104d72a46e)
![image](https://github.com/COS301-SE-2024/WorkWise-Central/assets/133756137/e9906b11-6f41-4d1a-9f08-720cc6aee26f)
In this example the icon for mangagement and the to TBD icons should still show in the second image 
- [ ] Change the navbar icon to show the 3 lines when the navbar is colapsed and the x when the navbar is open

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by BlockchainDlamini** [comment]
Done
