### ISSUE TITLE
Calander view for dashboard

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#260]
# Implementation Request

## Description

Please create and implement the calander view for the dasboard. Make sure to finish all the deliverables.

## Deliverables

- [x] Make a calander 
- [x] Make the calender show all the jobs the user has access to 
- [x] Allow the user to togel beteen a montly weekly and daily view
- [x] Allow any of the jobs on the calender to be clickable. When clicked on it should show the job card modal (the modal that is linked to the view job button from the manger table) 

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
I added @KumbiraiShonhiwa so long, if this changes, please change the assignee to the correct person.

**Comment by CodeHermez** [comment]
This view has been routed to the home page and is done, just hasn't pushed the final one to dev but a demo of the one with mock data and no clickable edit is on dev rn, I've close the issue
