### ISSUE TITLE
Use Case Diagrams 

### ISSUE THREAD

**Issue by KumbiraiShonhiwa** [COS301-SE-2024/WorkWise-Central#3]
Draw use case diagrams for the following sub systems:

1. Authorization and Authentication
2. Account Management
3. Manager Job Management
4. Employee Job Management
5. Manager Inventory Management
6. Employee Inventory Management
7. Real-time Communication and Notification System
8. Task and Reporting System
9. Feedback Management System

**Comment by JessBloem** [comment]
The use case diagrams for the following have been creted: 
- client subsystem
- authentication and autherisation 
- job subsystem 
- employee subsystem
