### ISSUE TITLE
Sign up update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#318]
# Update Request

## Description

Please update sign up in accourdance with the deliverables below

## Deliverables

- [x]  Check uniqueness of usernames when the user creates their own username

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
There's an issue, where the response from the api says the username does not exist when it already exist. will speak to Hamza to find out what the problem is because its occuring the in the frontend

**Comment by KumbiraiShonhiwa** [comment]
completed
