### ISSUE TITLE
Styling update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#319]
# Update Request

## Description

Please update the styling in acourdance with the deliverables below

## Deliverables

- [x] Ensure that the colour of selected items in dropdown menus are visible in dark mode (This is an issue in the province dropdown in create company and in the some of the edit modals)
- [x] Make sure that font sizes do not effect the modal. This is an issue with the view Job modal

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
completed
