### ISSUE TITLE
Dashboard update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#321]
# Update Request

## Description

Please update the dashoard in accordance with the deliverables below

## Deliverables

- [x] Move everything except the calendar into a statistics tab under dashboard

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
completed
