### ISSUE TITLE
Change company update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#322]
# Update Request

## Description

Please update change company in accourdance with the deliverables below

## Deliverables

- [x] Make sure the employeeId used changes when the user changes companies

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
done
