### ISSUE TITLE
Create company update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#326]
# Update Request

## Description

Please complete the deliverables below

## Deliverables

- [x] In the create company modal, add a clearing button to province
- [x] Ensuure that province is required
- [x] The create company button doesn't work. (he userId is null) 

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by CodeHermez** [comment]
this works properly now
