### ISSUE TITLE
Create client update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#328]
# Update Request

## Description

Please update create client in accordance with the deliverables below 

## Deliverables

- [x] Add proviance to create client
- [x] Make sure create client actually creates a client
- [x] Remove the house number and change complex to be complex/building and add hint text prop to show that you can also add the unit number or the house number in the textbox
- [x] The south african ID still needs to be made optional 
- [x] Remove the username field for client. Clients don't have accounts in the system
- [x] The add client button still doesn’t work 
- [x] The preferred language input field is not aligned with the rest of the input boxes

**Comment by Hamza-Mokiwa** [comment]
Done in backend.

**Comment by CodeHermez** [comment]
This issue is done in the frontend
