### ISSUE TITLE
Add employee implementation

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#332]
# Implementation Request

## Description

Please complete the following deliverables. Please note this is dependant on the implementation of the invite system in the backend. 

## Deliverables

- [x] Implement the add employee modal

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by CodeHermez** [comment]
employee gets added successfully i tried it with a employee called Craig Federigi in the my company
