### ISSUE TITLE
Inventory - frontend

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#337]
# Feature Request

## Description

Please create the frontend for the inventory system in accordance with the deliverables below

## Deliverables

- [x] A table view for the inventory 
- [ ] Add inventory modal
- [x] Update inventory modal 
- [x] Delete inventory 
- [x] Make sure the structure and layout of inventory is the same as that of client, employee and job

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
there's an issue with add. its saying someting about the company id i'll add a screen shot
![image](https://github.com/user-attachments/assets/0f95a842-1886-4c05-a674-49677be8b004)
