### ISSUE TITLE
Create tutorials

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#338]
# Feature Request

## Description

Please create the tutorials for the system in accordance with the deliverables below

## Deliverables
- [x] Add images for tutorial

Add tutotials for the following:
- [x]  Sign up 
- [x] Sign in 
- [x] Calander 
- [x] How to use the tables (the action buttons)
- [x] Add client 
- [x] Edit client 
- [x] View client
- [x] Add employee 
- [x] Edit employee 
- [x] View employee
- [x] Add job
- [x] Edit job
- [x] View job 
- [x] User settings 
- [x] Company settings 
- [x] How to log out
- [x] Changing theme 
- [x] Managing companies

**Comment by JessBloem** [comment]
The issue has not been completed on time. The due dates have been updated

**Comment by CodeHermez** [comment]
did not add images for calendar and job and addejob because they are getting updated
