### ISSUE TITLE
Automated integration/e2e tests

### ISSUE THREAD

**Issue by Hamza-Mokiwa** [COS301-SE-2024/WorkWise-Central#34]
# Feature Request

## Description
Integration/e2e tests must run when making PRs to the `develop` and `main` branch

## Deliverables

- [ ] Create end-to-end test for everything that has been created

**Comment by JessBloem** [comment]
Please update or clode this issue. It is past it's due date

**Comment by Hamza-Mokiwa** [comment]
Integration tests are done. e2e outstanding

**Comment by JessBloem** [comment]
Closing this issue and making a new one with what still needs to be done
