### ISSUE TITLE
FAQ update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#354]
# Update Request

## Description

This is from the meeting with Micheal

## Deliverables 
- [x] Number it the questions
- [x] bolden question
- [x] Lessen elevation and number the questions and style

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by CodeHermez** [comment]
fixed this and also made the color of the question and answer distinguishable

![Uploading Screenshot 2024-07-19 182708.png…]()
