### ISSUE TITLE
Notification frontend

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#363]
# Feature Request

## Description

Please create the notification system in the frontend. At the moment @Hamza-Mokiwa and @JessBloem need to discuss how it will work in the backend. The issue will be updated with deliverables once they know how it will be structed in the backend

## Deliverables

- [x] Create a page that displays the list of notifications 
- [x] Add option to see all notifiactions (read and unread)
- [x] Add option to see unread notifications
- [x] Add an option to see read notifications 

## Additional information
Refere to github or linked in. The notifications will need to be clickable, but we are not sure how to do that yet. Will update the issue when we have think of something

**Comment by KumbiraiShonhiwa** [comment]
completed
