### ISSUE TITLE
Inventory update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#366]
# Update Request

## Description

Pleas update inventory in accordance with the deliverables below

## Deliverables

- [x] Add inventory find an icon that is more suitable for the operation
- [x] Change the name of an inventory item to product name
- [x] Don't shallow copy the data in inventory so that it gets changed in inventory
- [x] On the edit inventory the button shouldn't say “create” it should say “save”

**Comment by KumbiraiShonhiwa** [comment]
all is sorted
