### ISSUE TITLE
Logout update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#367]
# Update Request

## Description

Please update in accordance with the deliverables below

## Deliverables

- [x] For logout clear the localstorage instead of sessionstorage because code still clears session storage

**Comment by KumbiraiShonhiwa** [comment]
it clears local storage but there's the problem of being able to access the dashboard is still there. Need to use conditional rendering to say if the user is logged in then they can access the side. if not redirect the the log in screen
