### ISSUE TITLE
repair the more dropdown on the all tables

### ISSUE THREAD

**Issue by KumbiraiShonhiwa** [COS301-SE-2024/WorkWise-Central#388]
# Chore

## Description

The more dropdown has an issue where the dropdowns are appearing in the left corner instead of below the row of the selected item
## Deliverables 

- [x] update the clients table
- [x] update the jobs table
- [x] update the employees table

### Note for Contributors:

**Note: Please follow the template when submitting feature requests. Issues that do not follow the template may be closed without notice.**

**Comment by JessBloem** [comment]
I am not sure what this issue is refering to. Will confirm and then review
