### ISSUE TITLE
Navbar update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#394]
# Update Request

## Description

Please update the navbar n accordance with the deliverables below

## Deliverables

- [x] Move the company name to the top ribbon instead of being in the navbar. Add the company’s logo next to the name
- [x] Remove the logout from the navbar 
- [x] Rename “BackLog” to “Job Board” and move it to be in the dashboard
- [x] #398
- [x] The Hamburger icon should stay a hamburger icon when clicked (right now it becomes an x)
- [x] When the navbar is closed and you click on something it open up again, it should stay closed instead.

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
done
