### ISSUE TITLE
Design Specification for demo 1

### ISSUE THREAD

**Issue by KumbiraiShonhiwa** [COS301-SE-2024/WorkWise-Central#4]
Create wireframes and protoype designs to create a concrete idea of the frontend design
The following need to be accomplished:

1. Sign up
2. Register Company
3. Log in
4. Allocate Clients
5. Update Profile
6. Create Client

Each these pages should have wireframes with a basic color scheme and suggested color palette. Wireframes should be for both mobile and desktop views.

**Comment by CodeHermez** [comment]
👍🏿 ill work on it

**Comment by JessBloem** [comment]
The wireframes for the following has been created:

1. Splash page
3. Sign up
4. Sign up flow 
5. Register a company 
6. Join a company
7. Log in
9. Create Clients
10. Add Employee
11. Add job
12. Create Job
13. Dashbaord 
14. Client desk
15. Employee desk
