### ISSUE TITLE
Register Company

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#455]
# Update Request

## Description

Please update register company in accordance with the deliverables below

## Deliverables

- [x] Integration doesn't work (Undefined reference of Id). Please fix it.
- [x] Choosing the type of business is not clicking properly
- [x] Make the choose type of business field optional

**Comment by CodeHermez** [comment]
@JessBloem im waiting on hamza for this so that he returns me the employee so that it will be able to redirect other than that it works rn, so ill keep it here until he does so

**Comment by Hamza-Mokiwa** [comment]
It should be there now. Just need to check in 2 mins. Give me 5 minutes

**Comment by CodeHermez** [comment]
i finished this yesterday and it works

**Comment by JessBloem** [comment]
This modal's integration is not working. I will update the issue with what still needs to be done.

**Comment by JessBloem** [comment]
All done thank you
