### ISSUE TITLE
Create client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#457]
# Update Request

## Description

Please update the create client modal in accordance with the deliverables below

## Deliverables

- [x] Add from validation (ensuring that the save button is onlt clickable when the validation passes)
- [x] The company may not have both email and phone number, can we make only 1 of them required. (i.e. in some cases they can add a email and in other cases they can add a phone number but they can never leave both open)
- [X] Make ‘ID of client’ optional

**Comment by CodeHermez** [comment]
@JessBloem added the other stuff i dont know what you mean by company may have email and phone number

**Comment by JessBloem** [comment]
Done thank you
