### ISSUE TITLE
Add employee

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#458]
# Update Request

## Description

Please update the add employee in accordance with the deliverables below

## Deliverables

- [x] Needs to send an invite to that user to join the company, not add them directly (work with @Hamza-Mokiwa on this, he did invites)

**Comment by CodeHermez** [comment]
@JessBloem i checked the second point roles coming back as undefined is in backend

**Comment by CodeHermez** [comment]
@JessBloem could you please create an endpoint that checks if an employee with the username that's passed is in the company kind of like the user/exists/username endpoint you made for kumbi, other than that everything else is done on this issue but ill keep it open

**Comment by JessBloem** [comment]
This issue was not completed. It is being edited to refelect what needs to still be done

**Comment by JessBloem** [comment]
This issue was not completed. It is being edited to refelect what needs to still be done. I know that backend was blocking this issue. I believe it is working now. Please let me know if there is any issues

**Comment by JessBloem** [comment]
Still not done

**Comment by CodeHermez** [comment]
sorry this issue is done, its just the thing of not making it required and I've fixed that
