### ISSUE TITLE
Edit Employee

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#459]
# Update Request

## Description

Please update the edit employee modal in accordance with the deliverables below
## Deliverables

- [x] The role dropdown needs to exclude the owner role
- [x] The superior and subordinate dropdowns need validation to check that someone selected as a superior is not also selected as a subordinate (this is checked in the backend and will throw an error)

**Comment by CodeHermez** [comment]
@JessBloem 👍🏿 this is done

**Comment by JessBloem** [comment]
Done, thank you
