### ISSUE TITLE
Delete employee

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#460]
# Update Request

## Description

Please update the delete employee in accordance with the deliverables below

## Deliverables

- [x] Please fully integrate it

**Comment by CodeHermez** [comment]
@JessBloem this is integrated its just that it throws a 500 in the backend

**Comment by CodeHermez** [comment]
idk if i should keep it opened or should I close it cause I told hamza about it and he said there was a discussion between which endpoint should have it, it it should be emploee/... or company/...

**Comment by JessBloem** [comment]
Keep it open. Will talkto him about it

**Comment by JessBloem** [comment]
Okay so you should use the employee/delete endpoint. I am having a look at it right now to see what the issue with the internal server error is

**Comment by JessBloem** [comment]
The issue with delete employee is fixed

**Comment by CodeHermez** [comment]
> The issue with delete employee is fixed

implemented this fix in front end aswell

**Comment by JessBloem** [comment]
This is done, thank you
