### ISSUE TITLE
Kanban

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#462]
# Update Request

## Description

Please update the kanban in accordance with the deliverables below

## Deliverables

- [x] Height is too small 
- [X] Moving cards don’t save 
- [x] Display the image of the job card in the kanban

**Comment by CodeHermez** [comment]
@JessBloem this is done i just need you to check it, but give me 2 min ill push to dev in 5 min

**Comment by JessBloem** [comment]
Done thank you
