### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#463]
# Update Request

## Description

Please update the  in accordance with the deliverables below

## Deliverables

Tutorials
- [x] Add a search bar

FAQ
- [x] Add a search bar

**Comment by CodeHermez** [comment]
faq is not long enough to need a search bae

**Comment by CodeHermez** [comment]
@JessBloem ill leave the adding the clickable steps till the end cause its going to take too long and i cant do it now cause ive got alot of other stuff to do right now, i hope you understand 🙏🏿

**Comment by JessBloem** [comment]
Not everything was completed so I will update the issue to show what is outstanding

**Comment by JessBloem** [comment]
Not everything was completed so I will update the issue to show what is outstanding
