### ISSUE TITLE
Splash page

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#464]
# Update Request

## Description

Please update the splash page in accordance with the deliverables below

## Deliverables

- [x] Add tutorial
- [ ] #524
- [ ] #525
- [x] The buttons on the header is rounded but all the buttons in the system is square. Please make them square as well
- [x] Please change "Get Started" button to say "Sign up" and also be a solid blue colour with white text so that it looks uniform when compared to the buttons on the header

## Additional Information

The extra marketing stuff that is currently below the the original splash page is lacking a bit is styling. It does not look uniform compaired to the rest of the system. If it seems that it will take too long to fix up then we can even scrap it and go baack to the prvious version

**Comment by KumbiraiShonhiwa** [comment]
marketing is done for light mode

**Comment by JessBloem** [comment]
Done thank you
