### ISSUE TITLE
Sign up

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#466]
# Update Request

## Description

Please update sign up in accordance with the deliverables below

## Deliverables

- [ ] You can’t remove the profile picture once you added it

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/6964d498-0c6f-4176-91c9-f7c5eb8f65c5)
there's an internal server error witht the image upload endpoint. will ask hamza for help

**Comment by JessBloem** [comment]
The date thing has not been sorted. The issue will be reopened, and updated with what needs to be finished

**Comment by KumbiraiShonhiwa** [comment]
@Hamza said that he'll sort out the profile picture intgeration

**Comment by JessBloem** [comment]
This issue was not completed. It will be updated with what is left

**Comment by JessBloem** [comment]
New issue has been made this one is being closed
