### ISSUE TITLE
Edit client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#467]
# Update Request

## Description

Please update edit client in accordance with the deliverables below

## Deliverables

- [x] Doesn’t use the same toasts as all the other buttons
- [x] Doesn’t reload after it is done
- [ ] Any field you try to update get removed completely after being saved. For example if the name if “Jess” and I update it to be “Jessica”, then that client’s name disappears

**Comment by JessBloem** [comment]
There is an issue with loading the table. I think th eissue is in the backend. I will review when I am able to access the edit client button

**Comment by JessBloem** [comment]
The first and second issue has not been sorted. @KumbiraiShonhiwa please check that a toast comes up when the user clicks on save. Currently nothing comes up. The last issue is still there. If you are not sure what I am talking about, please let me know, I'll show you

**Comment by KumbiraiShonhiwa** [comment]
spoke to hamza and he said he'll sort out the issue in the backend. because it updates in the frontend but deletes in the backend

**Comment by JessBloem** [comment]
Since this is a backend issue, I will close this issue
