### ISSUE TITLE
Delete client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#472]
# Update Request

## Description

Please update delete client in accordance with the deliverables below

## Deliverables

- [x] Please integrate delete client. Client delete URL should have query parameters

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/9a9c28e9-af9c-402c-8f5d-09a95187b45c)
 hello im experiancing an internal server error

**Comment by JessBloem** [comment]
@Hamza-Mokiwa please have a look if the issue is in the backend or frontend

**Comment by Hamza-Mokiwa** [comment]
It is fully tested and working in backend, with #564 . It should work once merged

**Comment by Hamza-Mokiwa** [comment]
I'm waiting for Kumbi's approval on the PR

**Comment by JessBloem** [comment]
There is still a issue with this. I will update the issue

**Comment by JessBloem** [comment]
This has not been completed. Will be updated

**Comment by JessBloem** [comment]
Done thank you
