### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#475]
# Update Request

## Description

Please update the  in accordance with the deliverables below

## Deliverables

- [ ] #527
- [x] Make sure the actions button bring the 3 actions (view, edit and delete up) 
- [x] If not created already, create a view modal for teams 
- [x] If not created already, create a edit modal for teams

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/9e619f3a-bc4b-43d3-b73e-2f477011fc04)
im having an issue with the employee/detailed/id endpoint

**Comment by KumbiraiShonhiwa** [comment]
integration is complete, howver there are issues with the values not updating. 
all the response from the endpoints say success. 
delete works but the teams endpoint shows all the teams (there's no other endpoint for company specific teams)
create team works

**Comment by JessBloem** [comment]
There is still an issue with the integration. Will make a new issue with what needs to be done
