### ISSUE TITLE
Add inventory

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#477]
# Update Request

## Description

Please update the  in accordance with the deliverables below

## Deliverables

- [x] Make everything except the name optional

**Comment by JessBloem** [comment]
@KumbiraiShonhiwa please link the pr before chanign it to review request status

**Comment by JessBloem** [comment]
There is an issue with the endpoint because of something @Hamza-Mokiwa added. I am not able to reveiw this atm.

**Comment by Hamza-Mokiwa** [comment]
You didnt tell me until now💀

**Comment by JessBloem** [comment]
This has been done. Thank you
