### ISSUE TITLE
View job

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#483]
# Update Request

## Description

Please update view job in accordance with the deliverables below

## Deliverables

- [ ] Integrate Tasks items . Currently they disapear after closing the card and opening it again.
- [ ] Change the input box that shows the title to looking like this instead (make sure the delete button is also there and works):
![Image](https://github.com/user-attachments/assets/bd1f327e-5ccf-4fda-9724-8a764e417190)
- [ ] Make the navigation on the right sticky when scrolling down
- [ ] Put persistent hint on checks of tasks (bob mensioned this)
- [ ] Add the ability to edit comments
- [ ] Make the user clicks create task before the list of tasks are created (it is not clear that they need to click on the save button)
- [ ] Restrict size of images
- [ ] Assign employee to task (must allow multiple employees to be assigned)
- [ ] Remove the button for update job status (Ask bob). When they click on a different status it should update
- [ ] Integrate log stock usage
- [ ] Add ability to edit stock usage
- [ ] Integrate generate invoice 
- [ ] When changing the status at the bottom it does not update on the top (by the job details). Only updates when reloading the job card

**Comment by JessBloem** [comment]
Some of the deliverables where not completed. This issue will be reopend and updated with what is left

**Comment by BlockchainDlamini** [comment]
Don't think you can reload a card

**Comment by JessBloem** [comment]
This issue was not mopleted in time. The issue will be updated to refelect what still needs to be done

**Comment by BlockchainDlamini** [comment]
@JessBloem, something funky is happening with the profile picture of users in the backend, I updated my profile picture but when I comment or load new comments, my old profile image is used

**Comment by BlockchainDlamini** [comment]
Simulating the trello tasklist header won't be possible due to the user's ability to edit the title of a tasklist

**Comment by JessBloem** [comment]
Not everything was completed on time. Will update the issue with what is left
