### ISSUE TITLE
Edit job

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#484]
# Update Request

## Description

[Provide a clear and concise description of what needs to be updated.]

## Deliverables

- [x] Move save button to actions section of the modal. Currently there are 2 buttons, there should only be one ( the one in the actions section of the modal at the bottom) 
- [x] The integration for this modal is not done correctly, it doesn't update the job. Hamza checked and confirmed that the endpoint works.
- [x] Not reloading when save is clicked
- [x] Chnaging the client does not actually save the changes. Please integrate this
- [x] In the list of assigned employees, please show the employees that are currently assigned

**Comment by JessBloem** [comment]
There is un uncompleted deliverable. This issue will be reopened and updated to only show what is still left to do

**Comment by BlockchainDlamini** [comment]
Will do moving of the save button during the coding session, it requires a component refactor

**Comment by JessBloem** [comment]
Plaese only move it to review request once everything is done. I can't review if there are missing deliverables. I am moving it back to in progress until the last deliverable is complete

**Comment by JessBloem** [comment]
This issue was not completed on time. This issue will be updated to reflect what still needs to be don

**Comment by JessBloem** [comment]
The update client does not work yet. @Hamza-Mokiwa please also have a look at it. 

@BlockchainDlamini I also see that you are using the client/all endpoint instead of the client/all/{cid} endpoint in the dropdown menu for changing a client. Please change it to using the client/all/{cid} endpoint.

**Comment by Hamza-Mokiwa** [comment]
UpdateClient works in the backend, when I checked very recently. But alright, I can check again

**Comment by BlockchainDlamini** [comment]
Resolved, eish hades Hamza

**Comment by JessBloem** [comment]
Done thank you
