### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#487]
# Update Request

## Description

Please update image uploading in accordance with the deliverables below

## Deliverables

- [x] Ensure user profile can be added when a user is created
- [x] Esnure user profile images can be upadated
- [x] Ensure that companies can add logos when created
- [x] Ensure that companies logo's can be updated
- [x] Ensure that the image uploading or job works

**Comment by Hamza-Mokiwa** [comment]
Just need to test if it works for jobs
