### ISSUE TITLE
Join company modal

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#488]
# Update Request

## Description

Please update the Join company modal in accordance with the deliverables below

## Deliverables

- [x] Ensure that the modal is fully integrated 
- [x] Ensure that the company dropdown is pulling data

**Comment by Hamza-Mokiwa** [comment]
Will check integration is fully done by Friday

**Comment by JessBloem** [comment]
This issue can't m closed if not fully done

**Comment by Hamza-Mokiwa** [comment]
It is done, we just needed to remove the JWT requirement in the backend (which I have done)
