### ISSUE TITLE
User story: Add Client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#49]
As a managerial user,
I want to be able to add clients to the system,
so that I can keep track of all the clients and their jobs

Acceptance criteria:
-[ ]The ability to add clients should only be available to users with appropriate permissions
-[ ]The user must be click on a add client button
-[ ]The user must be able to input the clients details
-[ ]The details must be saved to the database

**Comment by JessBloem** [comment]
Permissions will not be implemented in demo 1. It will be completed at a later stage

**Comment by CodeHermez** [comment]
fixed
