### ISSUE TITLE
Job

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#492]
# Update Request

## Description

It takes long to load the job table

## Deliverables

- [x] Check if there is a way to make the loading faster
- [ ] Add lazy loading

**Comment by JessBloem** [comment]
Adding this issue without any dates becuase it is not exactly a backlog issue

**Comment by Hamza-Mokiwa** [comment]
I may add pagination for things like the table to only retrieve 5-10; this may help the speed
