### ISSUE TITLE
Role-base-access Employees

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#503]
# Implementation Request

## Description

Add the following role-based-access

## Deliverables

- [x] Only allow the current employee to see the table of employees if the have any of the following permissions: "view all employees", "view employees under me"
- [x] Only render the edit button if the current employee has any of the following permissions: "edit all employees","edit employees under me"
- [x] Only render the add button if the current employee has any of the following permision: "add new employees"
- [x] Only render the delete button if the current employee has the followng permision: "remove any employees", "remove employees under me"

**Comment by CodeHermez** [comment]
@JessBloem roles base access has been implemented and works well

**Comment by JessBloem** [comment]
Done thank you
