### ISSUE TITLE
Role-based-access Client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#504]
# Implementation Request

## Description

Please add the followign role based access

## Deliverables

- [x] #529
- [x] Only show the edit button if the current employeehad any of the following permisssions: "edit all clients", "edit clients that are under me", "edit clients that are assigned to me"
- [x] Only show the add buttonif the current employee has the following permission: "add a new clients"
- [x] Only show the delet button if the current employee has any of the following permission: "remove any clients", "remove clients under me", "remove clients assigned to me"

**Comment by KumbiraiShonhiwa** [comment]
added the role based implementation

**Comment by JessBloem** [comment]
Done thank you
