### ISSUE TITLE
Role-base-access inventory

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#505]
# Implementation Request

## Description

Please add the following role-base-access to invetory

## Deliverables

- [x] #528
- [x] Only show the edit button if the current employee has the following permission: "edit all inventory"
- [x] Only show the add button if the current employee has the following permission: "add new inventory item"
- [x] Only show the delete button if the current employee has the following permission: "delete inventory item"

## Additional Information

[Any additional details or context that might be helpful.]

---

### Note for Contributors:

**Note: Please follow the template when submitting refactor requests. Issues that do not follow the template may be closed without notice.**

**Comment by KumbiraiShonhiwa** [comment]
added the role based implementation

**Comment by JessBloem** [comment]
Done, thank you
