### ISSUE TITLE
Toast consistancy

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#517]
# Update Request

## Description

Please update the toast system wide in accordance with the deliverables below

## Deliverables

- [x] Please make sure that the order of toats and reload are the same everywhere

**Comment by KumbiraiShonhiwa** [comment]
I have gone through the system, and made the toasts consistent. I may have missed some of them

**Comment by JessBloem** [comment]
The toasts on job actions are not in the same order. Will reopen this issue for the current sprint

**Comment by KumbiraiShonhiwa** [comment]
The job card toasts order are working correctly, the reloading for the job card actions doesn't make sense since they are still editing ( refering to change client and add members)
Since we are removing reloads, its redundant to add them only to remove them later

**Comment by JessBloem** [comment]
This is not fully complete. @CodeHermez please also make sure that this is done everywhere. @KumbiraiShonhiwa might miss a few

**Comment by JessBloem** [comment]
@CodeHermez @KumbiraiShonhiwa What is happening with this issue? Are the toasts for all the action in the system consistent now?

**Comment by CodeHermez** [comment]
the toasts are consistent now you can close this @JessBloem
