### ISSUE TITLE
Company setting update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#518]
# Update Request

## Description

Please update the company settings in accordance with the deliverables below 

## Deliverables

- [x] Reload on company settings. Make sure that the company settings reload to the same tab instead of moving to the company details tab
- [ ] #531
- [x] Make the colour picker show the current colour when editing priority, tags and status 
- [ ] #530
- [x] Delete status has an issue
- [ ] #532

**Comment by KumbiraiShonhiwa** [comment]
hello the edit priority integration works. its not updating the item though?
![image](https://github.com/user-attachments/assets/85b676c5-4519-4f07-a5c7-11d7550c1ab4)

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/f8e9e71b-a8f6-4f9a-a401-bfb79d8c3381)
theres an issue with the edit staus
kyi;hdk

**Comment by KumbiraiShonhiwa** [comment]
@Hamza-Mokiwa

**Comment by JessBloem** [comment]
The frontend aspects have been completed. There are some issues with integration. Will create a new issue with what still needs to be done
