### ISSUE TITLE
Bulk update role

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#519]
# Update Request

## Description

Please complete the deliverables below 

## Deliverables

- [x] Add bulk role update

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/c08ab0d6-da5b-48f1-af5b-f10f55019a80)
im receving the same error with the single role update

**Comment by JessBloem** [comment]
I will have a look at this issue and le you know when it is fixed. For now I will put it in stuck

**Comment by JessBloem** [comment]
The issue has been fixed

**Comment by JessBloem** [comment]
This issue has not been complted. It will be updated with what is left
