### ISSUE TITLE
User story: Register company

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#52]
As a new or general user, 
I want to be able to register my company
so that my company may use the system for its management

Acceptance criteria:
- [ ] Given a new user, they must be able to register a new company when signing up.
- [ ] GIven a existing user, they must be able to register a new company.
- [ ] When registering a new company, the system must allow the user to enter all the details of the company
- [ ] The details of the company must be saved to the database 
- [ ] The user that registered the company must automatically be a part of the company
- [ ] The user that registered the company must automatically be a owner of the company

**Comment by CodeHermez** [comment]
Register company works
