### ISSUE TITLE
Add client

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#547]
# Update Request

## Description

Please update the add client modal in accordance with the deliverables below

## Deliverables

- [x] It does not have error toasts (i.e. it doesn't show a error message when it fails). Please add them. @KumbiraiShonhiwa make sure they are in the same order as the rest of the system. 
- [x] Also make sure thatt it shows a success message when it worked
- [x] Integration is not working.
- [x] Refresh after the add is done

**Comment by CodeHermez** [comment]
this works now

**Comment by JessBloem** [comment]
The integration on this is not working. There is also no error toast. I will reopen and update this issue

**Comment by JessBloem** [comment]
The integration on this is not working. There is also no error toast. I will reopen and update this issue
