### ISSUE TITLE
Client bug

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#552]
# Bug report 

## Description 
There are issues with create, edit and delete client.

## Deliverables
- [x] Please make sure create client is fully functional 
- [x] Please make sure edit client is fully functional 
- [x] Please make sure delete client is fully functional

**Comment by Hamza-Mokiwa** [comment]
@CodeHermez  said that createClient was not working, so I wlll look into it

**Comment by Hamza-Mokiwa** [comment]
It works
