### ISSUE TITLE
Remove reloads

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#553]
# Update Request

## Description

Please try to find a better way to update information instead of reloading the page. This is new develpment, therefore the deliverables and dates will change as we go along

## Deliverables

- [ ] Do reasearch and tests to find out what we can use instead of reloads. Perhaps look into sockets

**Comment by KumbiraiShonhiwa** [comment]
Having looked into it, i think we should use polling. 
basically we will call the specific get request for the subsystem. we add a time limit for when it updates. say every 5 seconds it makes the api call.

**Comment by KumbiraiShonhiwa** [comment]
all reloads have been removed

**Comment by JessBloem** [comment]
Solution has been found. Will make seperate issue for each of the subsystems for which this must be implmented

**Comment by JessBloem** [comment]
Solution has been found. Will make seperate issue for each of the subsystems for which this must be implmented
