### ISSUE TITLE
Integrate forgot password

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#560]
# Implementation Request

## Description

Please refer to the deliverables below 

## Deliverables

- [x] Please integrate the forgot password modal

**Comment by BlockchainDlamini** [comment]
Waiting endpoint to be sorted out first

**Comment by JessBloem** [comment]
Was not completed on time, due dates have been updated

**Comment by JessBloem** [comment]
Completed thank you
