### ISSUE TITLE
Edit team update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#594]
# Update Request

## Description

Please update the edit team in accordance with the deliverables below

## Deliverables

- [x] List of team members are not showing properly
- [x] Need to show the team leader’s name

**Comment by JessBloem** [comment]
Not showing the team leader's name

**Comment by KumbiraiShonhiwa** [comment]
![image](https://github.com/user-attachments/assets/d28d13be-12f0-49cc-8c53-c286403c9425)
it shows the team leader name?

**Comment by JessBloem** [comment]
This is done, thank you
