### ISSUE TITLE
Job update

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#601]
# Update Request

## Description

Update for use in automatic invioce generation

## Deliverables

- [x] Add time tracking per job per employee to jobs
- [ ] Add a list of inventory movement ids

**Comment by Hamza-Mokiwa** [comment]
I think these should be in a separate Collection, to prevent slowness in Jobs

**Comment by Hamza-Mokiwa** [comment]
Time tracking is complete in the backend
