### ISSUE TITLE
Additions to job card (view job)

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#602]
# Update Request

## Description

This is needed for the automatic inviocing system

## Deliverables

- [ ] Add a way for the emplyee can start, stop and pause time tracking on the job card

**Comment by BlockchainDlamini** [comment]
I don't know what time tracking implies, so I haven't added it

**Comment by JessBloem** [comment]
Not fully completed on time. Will update the issue
