### ISSUE TITLE
Invoice page

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#607]
# Implementation Request

## Description

BEtween the 2 of you please make the page for this

## Deliverables

- [x] Make a page, under jobs in the navbar, that shows all the invoices that have been made in the company
- [x] Allow invoices to be viewed
- [x] Allow invoices to be editied
- [x] Allow invoices to be deleted

**Comment by KumbiraiShonhiwa** [comment]
add the componets

**Comment by JessBloem** [comment]
@KumbiraiShonhiwa, thank you. I think there will have to be some updates to the structure of this page. Can we meet tomorrow to descuss it?
