### ISSUE TITLE
Client portal

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#608]
# Implementation Request

## Description

Between the 2 of you please create the frontend for the client portal in accordance with the deliverables below

## Deliverables

- [x] A place that shows the client all the jobs that they currently have with the company
- [x] A place to allow them to review any job that has been completed. 
- [x] A place that shows them all the invoices from the company. There should also be a pay button that will be integrated with a payment gateway

## Additional Information

Just make the frontend for this. Integration will happen when the backend has support for this.

**Comment by JessBloem** [comment]
@Hamza-Mokiwa please also refere to this issue to know what support is needed in the backend

**Comment by KumbiraiShonhiwa** [comment]
the route for the client portal: /client-portal

**Comment by JessBloem** [comment]
This has been done
