### ISSUE TITLE
Kanban - sprint 12

### ISSUE THREAD

**Issue by JessBloem** [COS301-SE-2024/WorkWise-Central#636]
# Update Request

## Description

Please update the Kanban in accordance with the deliverables below

## Deliverables

- [x] Add … to no status column. Only allow the actions on jobs not the column
- [x] Not all the jobs are showing, just the first job is showing

**Comment by CodeHermez** [comment]
added the check for if any of these job desired attributes are undefined they should be skipped to load the other jobs without causing a stop in the loading of the jobs when rendered
